sudo: required
language: go

branches:
  only: master

go:
  - 1.11.x

# no emails
notifications:
  email: false

before_script:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - go get -u golang.org/x/lint/golint

script:
  - make tests build

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo $DOCKER_PASSWORD | docker login -u="$DOCKER_USERNAME" --password-stdin;
      make latest;
    fi
    # remember these
    REPO_URL=`git config remote.origin.url`
    SSH_REPO=${REPO_URL/https:\/\/github.com\//git@github.com:}
    SHA=`git rev-parse --verify HEAD`
    # Deploy if there are some changes
    git diff --quiet
    if [ $? != 0 ]; then
      # Add all new files to staging phase and commit the changes
      git config user.name "Travis CI"
      git config user.email "travis@travis-ci.org"
      git add -A .
      git status
      git commit -m "Travis deploy ${SHA}"
      git push ${SSH_REPO}
    fi
