sudo: required
language: go

branches:
  only: master

go:
  - 1.11.x

# no emails
notifications:
  email: false

before_script:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - go get -u golang.org/x/lint/golint

script:
  - GO111MODULE=on make tests build

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo $DOCKER_PASSWORD | docker login -u="$DOCKER_USERNAME" --password-stdin;
      make latest;
    fi
