[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.4.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/prometheus/alertmanager"
  version = "0.15.2"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"
