apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "stargate.fullname" . }}
  labels:
    app: {{ include "stargate.name" . }}
    chart: {{ include "stargate.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

data:
  stargate.yaml: |
    slack:
      signing_secret: {{ default "" .Values.slack.signing_secret | quote }}
      verification_token: {{ default "" .Values.slack.verification_token | quote }}
      access_token: {{ default "" .Values.slack.access_token | quote }}
      authorized_groups:
{{ toYaml .Values.slack.authorized_groups | indent 8 }}

