apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "stargate.fullname" . }}
  labels:
    app: {{ include "stargate.name" . }}
    chart: {{ include "stargate.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "stargate.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "stargate.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "stargate.name" . }}-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - stargate
            - --port={{ .Values.port }}
            - --metric-port={{ .Values.metricPort }}
            - --config-file=/etc/stargate/config/{{ include "stargate.fullname" . }}.yaml
            - --debug={{ .Values.debugEnabled }}
            - --disable-slack-rtm={{ .Values.disableSlackRTM }}
            - --persistence-file=/data/alertstore.dump
            - --recheck-interval=2m
            {{- if .Values.externalURL }}
            - --external-url={{ .Values.externalURL }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.metricPort }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/stargate/config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "stargate.fullname" . }}
        - name: config
          configMap:
            name: {{ include "stargate.fullname" . }}
