apiVersion: apps/v1beta2
kind: Deployment

metadata:
  name: {{ include "stargate.fullname" . }}
  labels:
    app: {{ include "stargate.name" . }}
    chart: {{ include "stargate.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "stargate.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "stargate.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "stargate.name" . }}-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - stargate
            - --port={{ default 8080 .Values.port }}
            - --alertmanager-url={{ required "missing alertmanager url" .Values.alertmanager.url }}
            - --config-file=/etc/stargate/config/{{ include "stargate.fullname" . }}.yaml
            - --debug={{ .Values.debugEnabled }}
            {{- if .Values.externalURL }}
            - --external-url={{ .Values.externalURL }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ default 8080 .Values.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/stargate/config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "stargate.fullname" . }}
