{{- if .Values.ingress.enabled -}}
{{- $fullName := include "stargate.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress

metadata:
  name: {{ $fullName }}
  labels:
    app: {{ include "stargate.name" . }}
    chart: {{ include "stargate.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}

spec:
  tls:
    - hosts:
      - {{ required "missing externalURL" .Values.externalURL }}
      {{- if .Values.sans }}
{{ toYaml .Values.sans | indent 6 }}
      {{- end }}
      secretName: tls-{{ required "missing externalURL" .Values.externalURL | replace "." "-" }}
  rules:
    - host: {{ required "missing externalURL" .Values.externalURL }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
    {{- range $_, $host := .Values.sans }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
    {{- end }}
{{- end }}
