replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: sapcc/stargate
  tag: a8d24e32

# the port used to expose the stargate API
port: 8080

# whether debug is enabled
debugEnabled: false

# whether the slack RTM (Real Time Messaging aka the Bot) should be disabled
disableSlackRTM: true

# Slack configuration
slack:
  # username for slack messages
  user_name: Stargate

  # Slack signs the requests we send you using this secret
  # Confirm that each request comes from Slack by verifying its unique signature.
  # signing_secret: DEFINED-IN-SECRETS

  # This deprecated Verification Token can still be used to verify that requests come from Slack,
  # but we strongly recommend using the above, more secure, signing secret instead.
  # verification_token: DEFINED-IN-SECRETS

  # Use this token to authenticate the stargate
  # access_token: DEFINED-IN-SECRETS

  # Access token to authenticate the stargate bot user
  # bot_user_access_token: DEFINED-IN-SECRETS

  # List of slack user groups whose members are authorized to silence alerts, create tickets, etc.
  # authorized_groups:
  #   - admin

  # Slack command to trigger actions
  # default: /stargate
  # command:

# Prometheus Alertmanager configuration
alertmanager:
  # # the URL of the Prometheus Alertmanager
  url: nil

# the stargate's URL
# externalURL: DEFINED-IN-SECRETS

# optional SANs used for the certificate
# sans:
  # - SAN

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ingress.class: nginx-internet
    kubernetes.io/ingress.class: nginx-internet
    vice-president: "true"
    disco: "true"

# values for stable/nginx-ingress chart
nginx-ingress-internet:
  enabled: false

  revisionHistoryLimit: 5
  rbac:
    create: true
  serviceAccount:
    create: false
    name: default

  controller:
    image:
      repository: sapcc/nginx-ingress-controller
      tag: "0.19.0"

    ingressClass: nginx-internet

    electionID: ingress-internet-controller-leader

    livenessProbe:
      initialDelaySeconds: 30

    kind: Deployment
    replicaCount: 3

    minReadySeconds: 60
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1

    config:
      http-snippet: |
        map $ssl_client_s_dn $ssl_client_s_dn_cn {
            default "anonymous";
            ~CN=(?<CN>[^/,\"]+) $CN;
        }
      location-snippet: |
        proxy_set_header X-REMOTE-USER $ssl_client_s_dn_cn;
      proxy-read-timeout: '300'
      proxy-body-size: '0k'
      server-name-hash-bucket-size: '128'
      map-hash-bucket-size: '128'
      worker-processes: '8'
      disable-ipv6: 'true'
      ssl-redirect: 'false'
      enable-underscores-in-headers: "true"

    extraArgs:
      # disabled until https://github.com/kubernetes/ingress-nginx/issues/3034 is fixed
      enable-dynamic-certificates: "false"
      annotations-prefix: ingress.kubernetes.io
      sync-period: 5m0s

    stats:
      enabled: true

    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/probe: "10254"

    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

      targetPorts:
        http: http
        https: https

    affinity:
      # don't co-locate replicas of the ingress controller on the same node
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app: nginx-ingress-internet
                key: component
                operator: In
                values:
                - controller

  defaultBackend:
    enabled: true
    replicaCount: 2
    minAvailable: 1

    image:
      repository: sapcc/defaultbackend
      tag: '1.4'
      pullPolicy: IfNotPresent

    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"

    affinity:
      # don't co-locate replicas of the ingress backend on the same node
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app: nginx-ingress-internet
                key: component
                operator: In
                values:
                - default-backend
